version: "3"
services:
  db:
    image: mysql:5.7
    environment:
    - MYSQL_DATABASE=go_gin_xorm_db
    - MYSQL_ROOT_PASSWORD=password
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306